# -*- coding: utf-8 -*-
"""HAckatonJ4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WVqrJrfJrLzICfmXC1wOC3jns4prVCPQ
"""

from google.colab import drive
drive.mount('/content/drive')

# ═══════════════════════════════════════════════════════
# CONFIGURACIÓN INICIAL
# ═══════════════════════════════════════════════════════
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import classification_report, confusion_matrix, roc_auc_score, roc_curve
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

# Configurar estilo
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (14, 7)
plt.rcParams['font.size'] = 10

print("Entorno listo para diagnóstico ML")

# ═══════════════════════════════════════════════════════
# 📥 CARGA DE DATOS (desde GitHub)
# ═══════════════════════════════════════════════════════
import requests, io

base_url = "https://raw.githubusercontent.com/AlejandroTenorioT/Zonas-WiFi-Inteligentes/main/"
files = ['network_events_curated.csv', 'clients_curated.csv',
         'access_points_curated.csv', 'ap_hourly_metrics_curated.csv']

data = {}
for f in files:
    try:
        url = base_url + f
        df = pd.read_csv(io.StringIO(requests.get(url).text))
        data[f.replace('_curated.csv','')] = df
        print(f" {f}: {df.shape}")
    except Exception as e:
        print(f" Error con {f}: {e}")

# Variables globales
events = data['network_events']
clients = data['clients']
aps = data['access_points']
metrics = data['ap_hourly_metrics']

# Convertir timestamps
metrics['timestamp_hour'] = pd.to_datetime(metrics['timestamp_hour'])
events['timestamp'] = pd.to_datetime(events['timestamp'])

# ═══════════════════════════════════════════════════════
# DIAGNÓSTICO EXPLORATORIO (EDA)
# ═══════════════════════════════════════════════════════

print("RESUMEN GENERAL DE MÉTRICAS:")
print(metrics.describe().round(2))

# 1. Distribución de estados de APs
fig1 = px.pie(aps, names='status', title='Estado de Access Points',
              color='status', color_discrete_map={'online':'#2ecc71', 'offline':'#e74c3c', 'dormant':'#f39c12'})
fig1.show()

# 2. Tasa de desconexión por AP (ordenado)
ap_disconnection = metrics.groupby('ap_name')['disconnection_rate'].mean().sort_values(ascending=True)
fig2 = px.bar(x=ap_disconnection.values, y=ap_disconnection.index, orientation='h',
              title='Tasa Promedio de Desconexión por AP (Mayor = Más Problemas)',
              labels={'x':'Disconnection Rate', 'y':'Access Point'},
              color=ap_disconnection.values, color_continuous_scale='YlOrRd')
fig2.update_layout(yaxis={'categoryorder':'total ascending'})
fig2.show()

# 3. Patrón horario de fallas
metrics['hour'] = metrics['timestamp_hour'].dt.hour
hourly_pattern = metrics.groupby('hour')['disconnection_rate'].mean()
fig3 = px.line(x=hourly_pattern.index, y=hourly_pattern.values, markers=True,
               title='Patrón Horario de Desconexiones',
               labels={'x':'Hora del día', 'y':'Disconnection Rate Promedio'})
fig3.add_vrect(x0=18, x1=22, annotation_text="Horario Estudiantil", annotation_position="top", fillcolor="blue", opacity=0.1)
fig3.show()

# 4. Correlaciones entre métricas
corr = metrics[['total_connections','total_disconnections','unique_clients','disconnection_rate']].corr()
fig4 = px.imshow(corr, text_auto='.2f', color_continuous_scale='RdBu_r',
                 title='Correlación entre Métricas de Red')
fig4.show()

# ═══════════════════════════════════════════════════════
# FEATURE ENGINEERING CON ENFOQUE SOCIAL
# ═══════════════════════════════════════════════════════

# Extraer zona del nombre del AP
aps['zona'] = aps['ap_name'].str.extract(r'_(.+?)_AP', expand=False)
aps['zona'] = aps['zona'].fillna('Desconocida')

# Ponderación social por zona (ejemplo basado en contexto de Cali)
# En producción: cruzar con datos del DANE, estratificación, ubicación de colegios
SOCIAL_WEIGHT = {
    'Hormiguero': 1.5, 'El Saladito': 1.5, 'Felidia': 1.3, 'La Leonera': 1.3,
    'Pichinde': 1.4, 'Navarro': 1.2, 'La Elvira': 1.1, 'Montebello': 1.0,
    'Los Andes': 1.0, 'La Castilla': 1.1, 'Desconocida': 1.0
}

aps['social_weight'] = aps['zona'].map(lambda x: SOCIAL_WEIGHT.get(x, 1.0))

# Unir métricas con información de APs
df_ml = metrics.merge(aps[['ap_name', 'status', 'zona', 'social_weight']], on='ap_name', how='left')

# Crear features temporales
df_ml['hour'] = df_ml['timestamp_hour'].dt.hour
df_ml['day_of_week'] = df_ml['timestamp_hour'].dt.dayofweek
df_ml['is_peak_hour'] = df_ml['hour'].isin([6,7,8,17,18,19,20]).astype(int)  # Horarios estudiantiles/laborales
df_ml['is_weekend'] = (df_ml['day_of_week'] >= 5).astype(int)

# Features de comportamiento de red
df_ml['connection_efficiency'] = df_ml['total_connections'] / (df_ml['total_disconnections'] + 1)
df_ml['auth_per_client'] = df_ml['total_auth'] / (df_ml['unique_clients'] + 1)
df_ml['events_per_client'] = df_ml['total_events'] / (df_ml['unique_clients'] + 1)

# 🎯 TARGET: "Riesgo de Falla Crítica"
# Combinamos: alta desconexión + alto impacto social
threshold_disconnect = df_ml['disconnection_rate'].quantile(0.7)
df_ml['target_critical'] = ((df_ml['disconnection_rate'] > threshold_disconnect) &
                           (df_ml['social_weight'] >= 1.2)).astype(int)

print(f"📊 Distribución del target (1 = Falla Crítica Social):")
print(df_ml['target_critical'].value_counts(normalize=True).round(3))

# ANÁLISIS TEMPORAL: ¿Cuándo ocurren más fallas?
ap_metrics['timestamp_hour'] = pd.to_datetime(ap_metrics['timestamp_hour'])
ap_metrics['hour'] = ap_metrics['timestamp_hour'].dt.hour
ap_metrics['day_of_week'] = ap_metrics['timestamp_hour'].dt.day_name()

print(" con mayor tasa de desconexión:")
hourly_issues = ap_metrics.groupby('hour')['disconnection_rate'].mean().sort_values(ascending=False).head(5)
print(hourly_issues)

# Gráfica de calor: hora vs día de la semana
pivot_heatmap = ap_metrics.pivot_table(
    values='disconnection_rate',
    index='day_of_week',
    columns='hour',
    aggfunc='mean'
)

plt.figure(figsize=(14, 6))
sns.heatmap(pivot_heatmap, annot=True, fmt='.2f', cmap='YlOrRd', cbar_kws={'label': 'Disconnection Rate'})
plt.title('Mapa de Calor: Tasa de Desconexión por Hora y Día')
plt.xlabel('Hora del día')
plt.ylabel('Día de la semana')
plt.tight_layout()
plt.show()

# PREPARAR DATOS PARA MAPA DE EQUIDAD DIGITAL
# Extraer zona/barrio del nombre del AP
access_points['zona'] = access_points['ap_name'].str.extract(r'_(.+?)_AP')

# Cruzar métricas con información de APs
ap_summary = ap_metrics.groupby('ap_name').agg({
    'disconnection_rate': 'mean',
    'total_connections': 'sum',
    'unique_clients': 'mean',
    'total_events': 'sum'
}).reset_index()

ap_summary = ap_summary.merge(access_points[['ap_name', 'status', 'zona']], on='ap_name', how='left')

print("RESUMEN POR ZONA (para el agente estratégico):")
zona_summary = ap_summary.groupby('zona')[['disconnection_rate', 'unique_clients', 'total_connections']].mean().sort_values('disconnection_rate', ascending=False)
print(zona_summary.round(3))

# Guardar para usar después
ap_summary.to_csv('ap_summary_calibrated.csv', index=False)
print("\ Datos procesados guardados en 'ap_summary_calibrated.csv'")

# ═══════════════════════════════════════════════════════
# ENTRENAMIENTO DE MODELOS COMPARATIVOS
# ═══════════════════════════════════════════════════════

# Seleccionar features
features = ['disconnection_rate', 'total_connections', 'total_disconnections',
            'unique_clients', 'total_auth', 'hour', 'day_of_week', 'is_peak_hour',
            'is_weekend', 'connection_efficiency', 'auth_per_client', 'social_weight']

X = df_ml[features].fillna(0)
y = df_ml['target_critical']

# Split estratificado
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42, stratify=y
)

# Escalar para modelos sensibles
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Diccionario de modelos a comparar
models = {
    'Random Forest': RandomForestClassifier(n_estimators=100, max_depth=8,
                                           class_weight='balanced', random_state=42),
    'Gradient Boosting': GradientBoostingClassifier(n_estimators=100, max_depth=5, random_state=42),
    'Logistic Regression': LogisticRegression(class_weight='balanced', max_iter=1000, random_state=42)
}

results = {}
print("Entrenando modelos...\n")

for name, model in models.items():
    # Usar datos escalados solo para LR
    X_tr = X_train_scaled if name == 'Logistic Regression' else X_train
    X_te = X_test_scaled if name == 'Logistic Regression' else X_test

    model.fit(X_tr, y_train)
    y_pred = model.predict(X_te)
    y_proba = model.predict_proba(X_te)[:,1]

    results[name] = {
        'model': model,
        'auc': roc_auc_score(y_test, y_proba),
        'accuracy': (y_pred == y_test).mean(),
        'report': classification_report(y_test, y_pred, output_dict=True),
        'y_proba': y_proba,
        'y_pred': y_pred
    }

    print(f"{name}:")
    print(f"   • AUC-ROC: {results[name]['auc']:.3f}")
    print(f"   • Accuracy: {results[name]['accuracy']:.3f}")
    print(f"   • F1-Score (clase crítica): {results[name]['report']['1']['f1-score']:.3f}\n")

# ═══════════════════════════════════════════════════════
#  EVALUACIÓN Y COMPARACIÓN VISUAL
# ═══════════════════════════════════════════════════════

# 1. Curvas ROC comparativas
plt.figure(figsize=(10, 7))
for name, res in results.items():
    fpr, tpr, _ = roc_curve(y_test, res['y_proba'])
    plt.plot(fpr, tpr, label=f'{name} (AUC={res["auc"]:.3f})', linewidth=2)
plt.plot([0,1], [0,1], 'k--', label='Aleatorio')
plt.xlabel('Tasa de Falsos Positivos')
plt.ylabel('Tasa de Verdaderos Positivos')
plt.title('Curvas ROC - Comparación de Modelos')
plt.legend()
plt.grid(alpha=0.3)
plt.tight_layout()
plt.show()

# 2. Matriz de confusión del mejor modelo
best_model_name = max(results, key=lambda x: results[x]['auc'])
best_res = results[best_model_name]

cm = confusion_matrix(y_test, best_res['y_pred'])
plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Normal', 'Crítico'], yticklabels=['Normal', 'Crítico'])
plt.title(f'Matriz de Confusión - {best_model_name}')
plt.ylabel('Real')
plt.xlabel('Predicho')
plt.tight_layout()
plt.show()

print(f"MEJOR MODELO: {best_model_name}")
print(f"Detalle de desempeño en clase CRÍTICA (la que más importa):")
print(classification_report(y_test, best_res['y_pred'], target_names=['Normal', '⚠️ CRÍTICO']))

# ═══════════════════════════════════════════════════════
# INTERPRETABILIDAD: ¿Qué factores predicen fallas?
# ═══════════════════════════════════════════════════════

# Usar el modelo de Random Forest para importancia de features
rf_model = results['Random Forest']['model']
feature_importance = pd.DataFrame({
    'feature': features,
    'importance': rf_model.feature_importances_
}).sort_values('importance', ascending=False)

fig = px.bar(feature_importance, x='importance', y='feature', orientation='h',
             title='Importancia de Features para Predecir Fallas Críticas',
             labels={'importance':'Importancia', 'feature':'Variable'},
             color='importance', color_continuous_scale='Viridis')
fig.show()

# INSIGHT CLAVE: Top 3 drivers de fallas
top_drivers = feature_importance.head(3)['feature'].tolist()
print(f"\nTOP 3 FACTORES QUE PREDICEN FALLAS CRÍTICAS:")
for i, driver in enumerate(top_drivers, 1):
    print(f"{i}. {driver.replace('_', ' ').title()}")

# ═══════════════════════════════════════════════════════
# DIAGNÓSTICO GEO-ESPACIAL PARA AGENTE ESTRATÉGICO
# ═══════════════════════════════════════════════════════

# Resumen por zona con métricas de impacto social
zona_diagnostic = df_ml.groupby('zona').agg({
    'disconnection_rate': 'mean',
    'unique_clients': 'mean',
    'social_weight': 'first',
    'target_critical': 'sum',  # Número de horas críticas detectadas
    'ap_name': 'nunique'  # Número de APs por zona
}).round(3).rename(columns={'ap_name': 'num_aps'})

zona_diagnostic['priority_score'] = (
    zona_diagnostic['disconnection_rate'] *
    zona_diagnostic['social_weight'] *
    np.log1p(zona_diagnostic['unique_clients'])
).round(2)

zona_diagnostic = zona_diagnostic.sort_values('priority_score', ascending=False)

print("RANKING DE ZONAS POR PRIORIDAD DE INTERVENCIÓN:")
print(zona_diagnostic[['disconnection_rate', 'social_weight', 'unique_clients', 'priority_score']].to_string())

# Visualización: Bubble chart (Impacto Social vs. Tasa de Falla)
fig = px.scatter(
    zona_diagnostic.reset_index(),
    x='disconnection_rate', y='social_weight',
    size='unique_clients', color='priority_score',
    hover_data=['num_aps', 'target_critical'],
    title='Matriz de Priorización: Fallas vs. Impacto Social',
    labels={'disconnection_rate':'Tasa de Desconexión', 'social_weight':'Peso Social'},
    size_max=60, color_continuous_scale='Reds'
)
fig.add_vline(x=threshold_disconnect, line_dash="dash", annotation_text="Umbral Falla")
fig.add_hline(y=1.2, line_dash="dash", annotation_text="Umbral Impacto Social")
fig.add_annotation(x=0.6, y=1.6, text="PRIORIDAD MÁXIMA<br>(Alta falla + Alto impacto)",
                   showarrow=True, arrowhead=2, bgcolor='rgba(255,0,0,0.1)')
fig.show()

# Guardar diagnóstico para el dashboard
zona_diagnostic.to_csv('zona_priority_diagnostic.csv')
print(f"\nDiagnóstico guardado: 'zona_priority_diagnostic.csv'")

# ═══════════════════════════════════════════════════════
# REPORTE FINAL: RECOMENDACIONES ACCIONABLES
# ═══════════════════════════════════════════════════════

print("\n" + "═"*60)
print("REPORTE DE DIAGNÓSTICO - CALIWIFI INCLUSIVO")
print("═"*60)

# Top 3 zonas críticas
top_critical = zona_diagnostic.head(3)
print(f"\nZONAS QUE REQUIEREN INTERVENCIÓN INMEDIATA:")
for zona, row in top_critical.iterrows():
    print(f"   • {zona}:")
    print(f"     - Tasa desconexión: {row['disconnection_rate']:.1%}")
    print(f"     - Usuarios promedio: {row['unique_clients']:.0f}")
    print(f"     - Score de prioridad: {row['priority_score']:.2f}")

# Recomendaciones por agente
print(f"\nRECOMENDACIONES POR AGENTE:")
print(f"""
   [Agente Operativo]
   • Monitorear especialmente las horas {df_ml[df_ml['is_peak_hour']==1]['hour'].unique().tolist()}
   • Alertar cuando disconnection_rate > {threshold_disconnect:.1%} en zonas con peso social ≥1.2
   • Modelo recomendado: {best_model_name} (AUC: {results[best_model_name]['auc']:.3f})

   [Agente Conversacional]
   • Preguntas clave a soportar:
     - "¿Qué zona tiene peor WiFi para estudiar ahora?"
     - "¿Cuándo es mejor conectarse en [zona]?"
     - "Reportar falla en mi ubicación"

   [Agente Estratégico]
   • Inversión prioritaria: {top_critical.index[0]} y {top_critical.index[1]}
   • Métrica de éxito: Reducir disconnection_rate en zonas con peso social ≥1.3
   • Impacto estimado: {top_critical['unique_clients'].sum():.0f} usuarios beneficiados directamente
""")

print(f"\nMÉTRICAS PARA EL PITCH:")
print(f"   • Precisión del modelo en clase crítica: {results[best_model_name]['report']['1']['precision']:.1%}")
print(f"   • Recall (detección de fallas reales): {results[best_model_name]['report']['1']['recall']:.1%}")
print(f"   • Zonas vulnerables priorizadas: {len(top_critical)}")
print(f"   • Potencial de impacto: +{zona_diagnostic['unique_clients'].sum():.0f} usuarios")